### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by GunaShekar02** [AASF-IIITM/aasf-website-backend#1]
Add error cases to documentation.

Check out `server/common/api.yml` file for the documentation. The very first API, i.e., `/users/login` has 4 responses, a 200 response for success, 400 for "User Not Found", 401 for "Invalid Password" and 500 for "Could Not Login". 

However the other APIs only have a success response. Add error responses similar to the first API for the other APIs as well.

This is how you would figure out the possible errors that could be thrown by the code:-
1. Note the route for the API you're trying to write error documentation for. For example, PUT request to `/users/password`.
2. Go to `server/routes.js` and see that any route that begins with `\users` is routed to the `usersRouter`. Go to the `usersRouter` file.
3. See that the function associated with PUT request to  `/password` is controller.changePassword.
4. Go to the `controller.js` file in the same folder and find the changePassword function.
5. In that function, observe that the controller is delegating the task to the changePassword function in `UsersService`
6. Go to that service function and see that there are 2 errors, a 400 and a 401 error that could be thrown. 
7. Document those errors in the `api.yml` file.

For a complete insight on how the flow works, checkout README.md.

**Comment by ampsteric** [comment]
I would like to work on this issue sir. please assign it to me.

**Comment by GunaShekar02** [comment]
Hey @ampsteric. Glad you want to contribute but I'm really sorry to inform that this repository is made to help the students of IIITM Gwalior as mentioned in the README. I hope you find other great repositories for contribution!

**Comment by tend2infinity** [comment]
@GunaShekar02 Sir , I would like to work on this issue

**Comment by GunaShekar02** [comment]
Sure @tend2infinity, go ahead
