### ISSUE TITLE
Add a feature for admins to add new admins

### ISSUE THREAD

**Issue by GunaShekar02** [AASF-IIITM/aasf-website-backend#10]
Currently, admins can only be created from the database. Add a feature to allow current admins to add new admins via an API so that we don't have to modify the database for adding new admins.

Suggested procedure:-
1. Accept new admin details from the request body, i.e., name and roll number.
2. Verify if the request-sender is an admin using the isAdmin middleware.
3. Upload the new user using the userModel with role as "admin"(all lowercase).

**Comment by GunaShekar02** [comment]
Test comment

**Comment by parthlaw** [comment]
I like to work on it..

**Comment by GunaShekar02** [comment]
That's great @parthlaw. Assigning it to you

**Comment by kailash360** [comment]
I would like to work on this issue

**Comment by GunaShekar02** [comment]
Sure @kailash360! Assigning it to you.

**Comment by sohan2410** [comment]
Can I also work on this issue

**Comment by GunaShekar02** [comment]
I think @kailash360 has removed their assignment, so you can go ahead with this @sohan2410.
