### ISSUE TITLE
Migrate to async/await

### ISSUE THREAD

**Issue by GunaShekar02** [AASF-IIITM/aasf-website-backend#11]
[`server/common/server.js`](https://github.com/AASF-IIITM/aasf-website-backend/blob/master/server/common/server.js) had a `listen` function where a `.then - .catch` chain is used to handle asynchronicity.

Since the rest of the application uses the async/await pattern, it would be better to migrate this to async/await pattern as well.

Bonus: Find out if there are other locations in the application where `.then - .catch` chains are used, and migrate them as well.

**Comment by Being-Maverick** [comment]
Hey @GunaShekar02 , I would like to work on this. Please assign it to me.

**Comment by GunaShekar02** [comment]
Hey @Being-Maverick. Glad you want to contribute but I'm really sorry to inform that this repository is made to help the students of IIITM Gwalior. I hope you find other great repositories for contribution! :)

**Comment by manishprivet** [comment]
Hi, I would like to work on this. Please assign it to me

**Comment by GunaShekar02** [comment]
> Hi, I would like to work on this. Please assign it to me

Sure @manishprivet
