### ISSUE TITLE
Add email field to User Model

### ISSUE THREAD

**Issue by GunaShekar02** [AASF-IIITM/aasf-website-backend#2]
Currently, the user model mainly captures the user roll number(as the primary key) and his/her name. 

We could add email to this model for future usage.

Things to be done:-
1. Add an email field in the User Model like you normally would in any of your application.
2. Go to `server/api/services/users.service.js` and find the uploadUsers function.
3. The users variable is an array of users as uploading in the CSV by the admin. [Sample CSV](https://docs.google.com/spreadsheets/d/1cCKq79B3jO3mMGYP6KVn42CKrc5BIbkDTCLX4RMi2JI/edit?usp=sharing).
4. So the users array would be something like:-
[
  {
    _id: "2018BCS-000",
    name: "Temp User"
  },
 {
    _id: "2019BCS-000",
    name: "Other User"
  },
]
5. Loop through this array and based on the roll number given, add an "email" field to each of these objects. For example, the object corresponding to the _id 2018BCS-000 should have the email id `bcs_2018000@iiitm.ac.in`. 

Don't worry about the 3 digit or 2 digit number in roll numbers, we'll upload the users csv according to our institute standards later on.

**Comment by MitanshiKshatriya** [comment]
Hi, looking for good issues for hacktoberfest. I would like to be assigned to it.

**Comment by GunaShekar02** [comment]
Hey @MitanshiKshatriya. Glad you want to contribute but I'm really sorry to inform that this repository is made to help the students of IIITM Gwalior. I hope you find other great repositories for contribution! :)

**Comment by MitanshiKshatriya** [comment]
Okay!

**Comment by hs2361** [comment]
Hi, I would like to take this issue. Can you please assign it to me?

**Comment by GunaShekar02** [comment]
Sure @hs2361, go ahead!
