### ISSUE TITLE
Reformat files according to Prettier configuration

### ISSUE THREAD

**Issue by hs2361** [AASF-IIITM/aasf-website-backend#20]
Pull request #12 added in a new Prettier configuration for the project. However not all the files have been reformatted according to this configuration (which can be found [here](https://github.com/AASF-IIITM/aasf-website-backend/blob/master/.prettierrc.js)).

It would be nice to have all the files consistently formatted by Prettier, as it would make the code more readable. You can integrate Prettier with the text editor of your choice, by following the directions given in the [Prettier docs](https://prettier.io/docs/en/editors.html).

**Comment by kunaljain0212** [comment]
Can I work on this, please? @GunaShekar02

**Comment by manishdangi98** [comment]
@kunaljain0212 sure
