### ISSUE TITLE
Remove development logs

### ISSUE THREAD

**Issue by GunaShekar02** [AASF-IIITM/aasf-website-backend#27]
[Line 216 in the file `events.service.js`](https://github.com/AASF-IIITM/aasf-website-backend/blob/master/server/api/services/events.service.js#L216) has an unnecessary development log. We'd like to remove that from production.

**Comment by XDRAGON2002** [comment]
I would like to work on this issue

**Comment by GunaShekar02** [comment]
Sure @XDRAGON2002, assigning it to you.

**Comment by XDRAGON2002** [comment]
Created pull request #31 fixing this issue.
