### ISSUE TITLE
Use functional loops

### ISSUE THREAD

**Issue by GunaShekar02** [AASF-IIITM/aasf-website-backend#28]
[The `uploadUsers` function in the `users.service.js` file](https://github.com/AASF-IIITM/aasf-website-backend/blob/master/server/api/services/users.service.js#L21) uses a `for` loop to iterate over a list of users and assign them their email ID. Since we used functional loops at other places in the code, we'd like to use one here too, instead of a `for` loop.

**Comment by abhikhatri67** [comment]
Hey @GunaShekar02,

Can I pick this up?

**Comment by XDRAGON2002** [comment]
I would like to work on this issue

**Comment by GunaShekar02** [comment]
Thanks for your interest @XDRAGON2002! Let's take PRs one at a time. Will assign you this once the previous issue is resolved and if anyone else hasn't claimed this yet.

**Comment by XDRAGON2002** [comment]
Opened PR #32 fixing this issue.

**Comment by XDRAGON2002** [comment]
I forgot to mention this issue in the PR and hence is still open, commenting for visibility.
