### ISSUE TITLE
Modify scores given to students

### ISSUE THREAD

**Issue by GunaShekar02** [AASF-IIITM/aasf-website-backend#29]
The [`events.service.js`](https://github.com/AASF-IIITM/aasf-website-backend/blob/master/server/api/services/events.service.js) file has 3 functions, `addGoodies`, `addWinners` and `markAttendance`. Students are given points according to the importance level of the event. The importance level ranges from 1-3 with 1 being lowest level of importance and 3 the highest.

Currently, the scores seem to be unevenly distributed for these functions:-
- Winners currently get `eventData.importance * 5 + (2 - index) * 5` points. Here we assume that the first winner is present in the 0th index of the array, second winner in the 1st index etc. For example, if the event importance is 2, the first winner gets `2 * 5 + 2 * 5 = 20` points. Second winner gets 15 points and the third winner gets 10 points.
- Goodie questions get `eventData.importance * 5` points. If the importance is 2, each winner for goodie questions get 10 points each.
- Attendance gets `eventData.importance * 5 + 5` points. If the importance is 2, each student attending the event gets 15 points.

We'd like the scores to be given in the following fashion:-
- Winners should be getting the highest number of points.
- Goodie points should be given the second highest number of points, a little lesser than the winners but higher than attendance.
- Attendance should be given the least number of points.
- Though we'd like attendance to be given least number of points, it shouldn't be much lesser than goodie points since we encourage students to attend events and not just try to win them.

Modify the functions to adjust the points according to the above specifications.

**Comment by XDRAGON2002** [comment]
Can you elaborate on how the current scoring is assigned ?

**Comment by GunaShekar02** [comment]
@XDRAGON2002 Added more details regarding the current scoring system in the issue description.

**Comment by XDRAGON2002** [comment]
I would like to work on this.

**Comment by GunaShekar02** [comment]
@XDRAGON2002 Sure, thanks! Before you move on to code, could you send the formulae you're thinking to resolve this issue? If they seem to be good then we can go ahead.

**Comment by XDRAGON2002** [comment]
I was thinking something along the lines of -

**Winners -**
eventData.importance * 5 + (4 - index) * 5

**Goodie questions -** 
eventData.importance * 5 + 5

**Attendance -**
eventData.importance * 5

I've simply swapped the values for goodie questions and attendance and for winners modified the formula so that the person at the third place (index 2) will always be 5 points ahead of the goodie questions, similarly the difference between goodie question and attendance is also 5.

I have taken eventData.importance * 5 as the base number of points alloted to everyone attending the event and added extra points for the goodie questions and the winners, such that all the winners score more than the goodie questions.

**Comment by GunaShekar02** [comment]
> @GunaShekar02 I was thinking something along the lines of -
> 
> **Winners -** eventData.importance * 5 + (4 - index) * 5
> 
> **Goodie questions -** eventData.importance * 5 + 5
> 
> **Attendance -** eventData.importance * 5
> 
> I've simply swapped the values for goodie questions and attendance and for winners modified the formula so that the person at the third place (index 2) will always be 5 points ahead of the goodie questions, similarly the difference between goodie question and attendance is also 5.
> 
> I have taken eventData.importance * 5 as the base number of points alloted to everyone attending the event and added extra points for the goodie questions and the winners, such that all the winners score more than the goodie questions.

That sounds good, go ahead!

**Comment by XDRAGON2002** [comment]
Opened PR #33 fixing this issue.
