### ISSUE TITLE
Add Forgot Password Feature

### ISSUE THREAD

**Issue by GunaShekar02** [AASF-IIITM/aasf-website-backend#3]
This is in continuation to issue #2 and it cannot be implemented before that is done. So please make sure that feature is implemented before this one.

In the current system, the admin has the rights to modify user details. This is very useful since students tend to forget the passwords they set for their accounts, so the admins can quickly change their password back to the default value.
But it is better to have a forgot password feature so that users can reset their passwords themselves.

Here's a standard implementation procedure for a forgot password feature:-
1. The process will be OTP verification via email. When user requests to change their password, an OTP will be sent to their mail and the user can enter the OTP along with the new password and their password will be changed.
2. Have an `otp` model which will store OTPs that were sent to an email ID. MongoDB allows you to set an expiry time on records, an OTP could have an expiry time of 1 hour.
3. When user requests for a change of password, a randomly generated OTP will be sent to the mail ID corresponding to the user's roll number and store this OTP in the `otps` table. (Nodemailer has already been setup in the application. Check the `server/common/config.js` file to set the email and password for testing)
4. When the user receives the OTP, they will hit another API providing the OTP and a new password.
5. Match the OTP with the one stored in the database and change the password if they match.

**Comment by hs2361** [comment]
I would like to work on this issue. I will try to use a reset password token instead of an OTP that the user would have to manually type. This token can be sent as part of a link to the user's email. The user can then reset their password if the token is verified.

**Comment by GunaShekar02** [comment]
Sure @hs2361, sounds good. Can you provide with a brief architecture(probably using draw.io flowchart) so we can get an idea about how you can go about implementing it?

**Comment by hs2361** [comment]
Here's the flow I have in mind. I just had a query regarding the /reset/:token GET route, because we cannot directly show the user a form. However the email link that we send to users can only send a GET request. This would need to be connected to the front-end.
![Reset Password](https://user-images.githubusercontent.com/51477130/94938167-19697000-04ee-11eb-9e46-39692ea11aa4.png)

**Comment by GunaShekar02** [comment]
I would suggest having a separate model from the Reset Password Tokens instead of including it in the user model itself. That model will solely be responsible for dealing with this issue.

And yes @hs2361, we cannot send a form from the backend.
We could do something like this:-
1. Create a new resetPasswordTokens model. (Probably having the token and roll number with a TTL(time to live), you don't have to explicitly add an expiry field, adding a TTL will automatically delete the record from the database after expiry).
2. /forgot POST: Add a token corresponding to the roll number. Send this token via email. The URL would not be of the backend, but of the frontend, something like:- `https://frontend.com/reset?token=...&roll=...`
3. When the user is redirected to this website via the link he received on his mail, he will be shown a form to enter new password.
4. Entering the password and clicking on a button would make a POST request to backend.com/reset with token and roll as body params. You first check if the token is valid and then reset his password.

So the overall flow is something like:-
POST backend/forgot -> Send email with link as frontend/reset?token=...&roll=... -> User fills a form and hits POST backend/reset -> Check token validity and reset password.

There is no additional GET request to the backend involved here.

Let me know what you think about this.

**Comment by hs2361** [comment]
I'll create a new Token schema as suggested. This will contain the token itself along with the roll number. One more suggestion, we don't need to send the roll number along with the link, because the roll number will be stored in this Token model itself. I don't understand how we're planning on having a 'front-end only' route. Visiting `https://frontend.com/reset?token=...` would require the API to define a /reset GET route also. If we keep this as front-end only, how do we show the form only to users having a verified token?

My suggestion was, that we keep a /reset/:token GET method defined in the API, which would send a `200 OK` if the token was verified against the database and a `400 Bad Request` otherwise. This can then be called on the front-end to show the user the reset password form. Then when the password is entered, it send a POST request to /reset containing the token in the request body.

**Comment by GunaShekar02** [comment]
@hs2361 It's not really required to show the frontend form to just the users who have a verified token. Users will send along their token along with the new password and if the token is not correct, they will receive an error message.

In case you want to perform the valid token check beforehand, you could do that too. When `https://frontend.com/reset?token=...` is visited, there will be a loading screen and the token will first be verified. If the token is invalid, an error message will be sent and the user will be redirected. If the token is valid, you could toggle a database parameter from false to true and that user can reset his password, and this is similar to what you're suggesting.

But the second approach seems to be quite an overhead to me. Sending the token and password at once and sending an error back in case of invalid token should work fine.

What do you think?

**Comment by hs2361** [comment]
Alright, so you're proposing sending the token along with the reset password form. But even then, I will have to define a /reset/:token GET route in the API, or else the client will just see "Cannot GET /reset". So how do you suggest we show the user the form without defining a GET route?

**Comment by GunaShekar02** [comment]
As I said, the reset route which will show the form will be on the frontend, a separate service developed on React.js and not something the backend should worry about. The URL which will be sent in mail will be of the form `https://frontend.com/reset?token=.......`
We'll change the base URL when we have our frontend ready.

**Comment by hs2361** [comment]
Alright so I can skip the GET route altogether then, and simply have a POST /reset route, where I can expect a token and a password. And of course, I would need a POST /forgot route as well.

**Comment by GunaShekar02** [comment]
Yes

**Comment by hs2361** [comment]
Alright, I'll work on this then.

**Comment by GunaShekar02** [comment]
This issue isn't solved yet if someone is looking to contribute!

**Comment by sohan2410** [comment]
I would like to work on this feature!

**Comment by GunaShekar02** [comment]
Sure @sohan2410! Could you come up with an architecture/flow chart before going ahead? You can take reference from the previous comments, but feel free to come up with new ideas.

**Comment by sohan2410** [comment]
Let's say 2020IMG-016 forgets the password

- User will send post request to /forgot-password API. This router will send alpha numeric OTP of length 6 to mail: img_2020016@iiitm.ac.in where email can be extracted from user id using string slicing. Or simple we can send n digit numeric OTP
- OTP will be store in otp model along with userId with a TTL
- User will receive mail containing link in the format frontend.com/reset-password?userId=2020IMG016&otp=ght8bv and OTP
- On clicking the above link user will redirect to reset password page where user can enter new & confirm password.
- Otherwise user can go to reset-password page where user have to fill the required details: userId, otp, new & confirm password.
- Here I'm assuming new & confirm password to be verified  from client side
- After submitting the required details, post request to /reset-password API along with userId, otp, password in body, this API will validate userId and checks otp is valid. After successful validation, password will be changed.

Also assuming userId format is yearbatch-rollno for eg: 2020IMG-016 will be verified from client side before sending any API request

**Comment by GunaShekar02** [comment]
> Let's say 2020IMG-016 forgets the password
> 
> * User will send post request to /forgot-password API. This router will send alpha numeric OTP of length 6 to mail: [img_2020016@iiitm.ac.in](mailto:img_2020016@iiitm.ac.in) where email can be extracted from user id using string slicing. Or simple we can send n digit numeric OTP
> * OTP will be store in otp model along with userId with a TTL
> * User will receive mail containing link in the format frontend.com/reset-password?userId=2020IMG016&otp=ght8bv and OTP
> * On clicking the above link user will redirect to reset password page where user can enter new & confirm password.
> * Otherwise user can go to reset-password page where user have to fill the required details: userId, otp, new & confirm password.
> * Here I'm assuming new & confirm password to be verified  from client side
> * After submitting the required details, post request to /reset-password API along with userId, otp, password in body, this API will validate userId and checks otp is valid. After successful validation, password will be changed.
> 
> Also assuming userId format is yearbatch-rollno for eg: 2020IMG-016 will be verified from client side before sending any API request

That sounds good to me! Just a few points:-
1. Email ID is already present in the user model, so you can directly use that.
2. Instead of a link, for now we can just send the OTP because our client is an app.
3. We'd have to perform necessary validations on the backend too because people can use tools like `curl` or `Postman` where validation won't be done.

- The input validations(new password and confirm password being equal) would be done in the controller.
- Database validation(existence of the user, OTP validity) will be done in the service.

Again, this is a feature we've been wanting for a long time and I highly appreciate taking time to solve these! Let me know if you have any other doubts!

**Comment by sohan2410** [comment]
> > Let's say 2020IMG-016 forgets the password
> > 
> > * User will send post request to /forgot-password API. This router will send alpha numeric OTP of length 6 to mail: [img_2020016@iiitm.ac.in](mailto:img_2020016@iiitm.ac.in) where email can be extracted from user id using string slicing. Or simple we can send n digit numeric OTP
> > * OTP will be store in otp model along with userId with a TTL
> > * User will receive mail containing link in the format frontend.com/reset-password?userId=2020IMG016&otp=ght8bv and OTP
> > * On clicking the above link user will redirect to reset password page where user can enter new & confirm password.
> > * Otherwise user can go to reset-password page where user have to fill the required details: userId, otp, new & confirm password.
> > * Here I'm assuming new & confirm password to be verified  from client side
> > * After submitting the required details, post request to /reset-password API along with userId, otp, password in body, this API will validate userId and checks otp is valid. After successful validation, password will be changed.
> > 
> > Also assuming userId format is yearbatch-rollno for eg: 2020IMG-016 will be verified from client side before sending any API request
> 
> That sounds good to me! Just a few points:-
> 
> 1. Email ID is already present in the user model, so you can directly use that.
> 2. Instead of a link, for now we can just send the OTP because our client is an app.
> 3. We'd have to perform necessary validations on the backend too because people can use tools like `curl` or `Postman` where validation won't be done.
> 
> * The input validations(new password and confirm password being equal) would be done in the controller.
> * Database validation(existence of the user, OTP validity) will be done in the service.
> 
> Again, this is a feature we've been wanting for a long time and I highly appreciate taking time to solve these! Let me know if you have any other doubts!

Wanted to know OTP should be alpha number of length n or n digit numeric. Please also specify 'n'.

**Comment by GunaShekar02** [comment]
@sohan2410 Let's go with a 6 digit numeric OTP

**Comment by sohan2410** [comment]
#41
