### ISSUE TITLE
Restructure user schema to separate achievements from user model

### ISSUE THREAD

**Issue by GunaShekar02** [AASF-IIITM/aasf-website-backend#30]
The current user schema has an [`achievements` property](https://github.com/AASF-IIITM/aasf-website-backend/blob/master/server/models/user.js#L51) that stores the list of events in which the student stood first, second and third. This is good when we'd like to add an achievement to a user, but this schema prevents us from deriving insights about event achievements, like fetching all winners of an event, since we'll have to iterate through arrays to search for an event.

We want to make a new model, an `Achievement` model which would contain the `userId`, `eventId`, and `position`(this would be a number datatype property). 
We have to modify the following to make this happen:-

- [ ] Create a new `Achievements` model in the [`models` directory](https://github.com/AASF-IIITM/aasf-website-backend/tree/master/server/models).
- [ ] Remove the [`achievements` property](https://github.com/AASF-IIITM/aasf-website-backend/blob/master/server/models/user.js#L51) from the existing user model.
- [ ] Fetch achievements of the user with the `eventName` populated in the [`getUserDetails` function](https://github.com/AASF-IIITM/aasf-website-backend/blob/master/server/api/services/users.service.js#L123).
- [ ] Modify the [`addWinners` function](https://github.com/AASF-IIITM/aasf-website-backend/blob/master/server/api/services/events.service.js#L145) to add winners to the newly created `Achievements` collection. Feel free to experiment with the input format.

**Comment by sohan2410** [comment]
I would like to work on this issue
