### ISSUE TITLE
Modify usage of default password

### ISSUE THREAD

**Issue by GunaShekar02** [AASF-IIITM/aasf-website-backend#35]
We currently don't explicitly assign a password to newly uploaded users. The `User` Model has a [`default` property set for `password`](https://github.com/AASF-IIITM/aasf-website-backend/blob/master/server/models/user.js#L21), and this is derived from the `.env` file.

This is not exactly ideal since we'd have to provide a hash instead of plaintext password which would then be hashed. 

Instead, we'd like to have a plaintext default password saved in the `.env` file, and have the [`users.service.js`](https://github.com/AASF-IIITM/aasf-website-backend/blob/master/server/api/services/users.service.js#L17) file hash this plaintext default password and add it to the user document before creating their records on the database.

**Comment by XDRAGON2002** [comment]
I would like to work on this.

**Comment by GunaShekar02** [comment]
@XDRAGON2002 go ahead!

**Comment by XDRAGON2002** [comment]
Opened PR #40 that fixes this issue.
