### ISSUE TITLE
Change profile pictures from base-64 to file storage

### ISSUE THREAD

**Issue by GunaShekar02** [AASF-IIITM/aasf-website-backend#4]
Currently, the `/users/dp` route accepts a base-64 encoded image as a user's profile picture and it is stored as the same in the database.

Using file storage instead of base-64 encoded images will offer a lot of benefits. Refer to Gaurav Sen's Tinder System Design [Video](https://www.youtube.com/watch?v=tndzLznxq40) on Youtube to know more about why this is so.

Here's what we can do:-
1. Create a folder for storing images outside the server folder.
2. Take form-data file input and upload the image file using multer(multer is already setup in the application, you can refer to [`server/api/controllers/admin/controllers/users/router.js`](https://github.com/AASF-IIITM/aasf-website-backend/blob/master/server/api/controllers/admin/controllers/users/router.js) for the same).
3. Store image path(or just the name of the image since path will be same for all images) in the database.
4. Develop a separate API for fetching the user's image(which will act similar to a CDN).

Suggestions are welcomed!

**Comment by GunaShekar02** [comment]
Definitely @Abhishek357.

**Comment by Abhishek357** [comment]
@GunaShekar02 @manishdangi98 I need some help -
I have created a folder profilePictures in public folder where I will be storing images but from which route(end-point) should I post(input form-data file) images, is it admin/users/upload or users/dp as both admins and users(who are not admin) will be uploading dp.

**Comment by GunaShekar02** [comment]
@Abhishek357 go for users/dp. The users/dp route is not restricted for just non-admins, admins can access normal user routes as well, so implementing the feature there will enable everyone to set their DPs.

**Comment by kunaljain0212** [comment]
Can I also work on this issue, please?

**Comment by kunaljain0212** [comment]
@GunaShekar02 @manishdangi98 
Can I also work on this issue, please?

**Comment by GunaShekar02** [comment]
You could do that @kunaljain0212, try to collaborate with Abhishek if possible. Since it was assigned to him earlier, if we have 2 PRs, we'll have to merge Abhishek's.
No harm in working though, it won't be marked spam!

**Comment by Abhishek357** [comment]
@GunaShekar02 @manishdangi98 while fetching users images using get request will there be a variable parameter in req which give information about user whose dp we want or we simply want dp of logged in user and in which format do you want its res?

**Comment by GunaShekar02** [comment]
@Abhishek357 The DP to be returned is the DP of the logged in user. Roll number of the logged in user is available in the req.user property. You can take reference from `getUserDetails` function in the users controller.
Coming to the type of response, please follow this approach of sending the file: https://stackoverflow.com/questions/13485933/createreadstream-send-file-http

**Comment by manishprivet** [comment]
Instead of using file storage, should we opt for object storage like S3 or Google Cloud Storage? It's generally preferred nowadays for an app to be stateless for scalability as well as for the benefits docker provides in development and deployment.

**Comment by GunaShekar02** [comment]
@manishprivet that's a great idea, we did consider that. But that comes with additional costs as well, right?

**Comment by manishprivet** [comment]
@GunaShekar02 First year me S3 ka 5gb is free, and then it's 1.6 rupees per GB per month :sweat_smile: 

For real world use case, ye S3 ka average pricing which I think would be for this app

![image](https://user-images.githubusercontent.com/54291836/95010023-e3d69b00-0643-11eb-8cde-44b17a86871f.png)

Google cloud is even more cheap, with always free option
![image](https://user-images.githubusercontent.com/54291836/95010038-ffda3c80-0643-11eb-8bc7-7176db65528f.png)

Aur iske upar agar extra laga to that's also comparable to S3, inshort less than 50rs per month
