### ISSUE TITLE
Implement Rate Limiter

### ISSUE THREAD

**Issue by GunaShekar02** [AASF-IIITM/aasf-website-backend#42]
Rate Limiting is an essential feature for a server to stop malicious users from executing a DOS attack. We'd like to implement a rate limiter in our server to allow a maximum of 100 requests every 10 minutes.

The [`express-rate-limit`](https://www.npmjs.com/package/express-rate-limit) npm package can be used for the same.

This can be included in the [`server.js`](https://github.com/AASF-IIITM/aasf-website-backend/blob/master/server/common/server.js) file where other services like `cors` have been implemented.

Stretch Task:- Write a unit test to verify whether the server throws an error when the number of requests exceed the limit.

**Comment by sohan2410** [comment]
I would like to work on this feature

**Comment by GunaShekar02** [comment]
Go ahead @sohan2410!

**Comment by sohan2410** [comment]
Can you guide on how to write such unit test?

**Comment by GunaShekar02** [comment]
> Can you guide on how to write such unit test?

[] Choose any `GET` API, maybe the API to fetch events. Hit that API using `supertest` as it is done in other unit tests.
[] Create a loop to hit that API multiple times.
[] Ensure that less than 100 requests are allowed, i.e., if you run the loop and hit the API for less than 100 times, there should be no error and events should be fetched successfully.
[] Ensure that more than 100 requests are not allowed, i.e., if you run the loop more than 100 times, the server should throw an error.
