### ISSUE TITLE
Convert res.send to res.json

### ISSUE THREAD

**Issue by GunaShekar02** [AASF-IIITM/aasf-website-backend#7]
Currently, all the controllers send a response back to the client using the res.send method. 
Convert all of them to res.json.

[Difference between the two](https://www.tutorialspoint.com/difference-between-res-send-and-res-json-in-express-js#:~:text=The%20res.,now%20treat%20it%20as%20text.&text=json%20function%20on%20the%20other,the%20response%20to%20the%20client.)

**Comment by RitikPandey1** [comment]
Hello @GunaShekar02 , I would like to take this, can you assign this task to me ?

**Comment by GunaShekar02** [comment]
Hey @RitikPandey1. Glad you want to contribute but I'm really sorry to inform that this repository is made to help the students of IIITM Gwalior. I hope you find other great repositories for contribution! :)

**Comment by RitikPandey1** [comment]
> Hey @RitikPandey1. Glad you want to contribute but I'm really sorry to inform that this repository is made to help the students of IIITM Gwalior. I hope you find other great repositories for contribution! :)

 I didn't know that this repository is for IIITM students , its ok i will find other projects.

**Comment by manishprivet** [comment]
Hi, I would like to work on this. Please assign it to me

**Comment by darkpanda08** [comment]
Hey @GunaShekar02, If only IIITM Gwalior students are allowed to contribute to this repository, then it goes against the Hacktoberfest's values. Please remove the Hacktoberfest label or else it can be marked as spam and will be ineligible.

**Comment by GunaShekar02** [comment]
@darkpanda08 I didn't know about that, sorry for that. I'll remove the hacktoberfest label :)

**Comment by Shikhar15606** [comment]
@GunaShekar02 Sir, I am from IIIT Gwalior
Can I work on this Issue

**Comment by GunaShekar02** [comment]
Sure @Shikhar15606, go ahead!
