### ISSUE TITLE
Replace unused variables with underscore

### ISSUE THREAD

**Issue by GunaShekar02** [AASF-IIITM/aasf-website-backend#8]
It's a convention to use underscores instead of normal variable names for unused variables. For example, a controller takes a request(req) and a response(res) parameter. There might be cases(example, GET requests) where we do not use the req parameter. So the req parameter can be changed to an underscore.

Find all unused variables in controllers and other files and replace them with underscores.

PS: It's not a good practice to have unused variables hanging around in code. By unused variables here, I mean those which are necessarily required to be accepted as parameters, i.e., you cannot skip the req parameter and just take the res parameter. In case you find any unused variables within the code which are not necessary(for example, logger has been imported in some files but not used), please remove them.

**Comment by RitikPPatel05** [comment]
Wow, I didn't knew about this.
I would like to work on this. Thank you!

**Comment by GunaShekar02** [comment]
Hey @RitikPPatel05. Glad you want to contribute but I'm really sorry to inform that this repository is made to help the students of IIITM Gwalior. I hope you find other great repositories for contribution!

**Comment by manishprivet** [comment]
I would like to work on it. Please assign it to me
