### ISSUE TITLE
Write Database backup scripts

### ISSUE THREAD

**Issue by GunaShekar02** [AASF-IIITM/aasf-website-backend#9]
Database backups are extremely important to avoid data loss in case of node failures or human errors.

Writing scripts for database backups is fairly simple. You can use [Mongoexport](https://docs.mongodb.com/database-tools/mongoexport/#bin.mongoexport) to export collections as JSON or CSV, or [Mongodump](https://docs.mongodb.com/database-tools/mongodump/#bin.mongodump) to dump the whole database. 

You may use `node-cron` or `node-schedule` npm libraries for running cron jobs to take timely database backups.

You may create a folder named scripts in the root folder and add your script to that. That script will be run independent of this server to avoid performance issues.

**Comment by Liopun** [comment]
@GunaShekar02 Can i start working on this?

**Comment by manishdangi98** [comment]
Hey, @Liopun  Glad, you want to contribute but I'm really sorry to inform you that this repository is made to help the students of IIITM Gwalior. I hope you find other great repositories for contribution! :)

**Comment by savi-1311** [comment]
@GunaShekar02 @manishdangi98  Sir can I work on this?

**Comment by GunaShekar02** [comment]
Sure @savi-1311, assigning it to you!
